parameters:
- name: BuildConfiguration
  displayName: Select BuildConfiguration
  type: string
  default: release
  values:
  - release
  - debug

trigger:
  branches:
    include:
    - buildd
    - hotfix/*
    - feature/*
  paths:
    exclude:
    - .azure-pipelines
    - LICENSE
    - README.md

resources:
  repositories:
  - repository: sharedTemplates
    type: github
    name: mnastp/nugget-app.YAMLTemplates
    endpoint: github.com_mnastp

variables:
- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/build') }}:
  - group: nuget-prod
- ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/build') }}:
  - group: nuget-dev

pool:
  vmImage: windows-latest #require windows agent because we have a .NET Framework target

#extends:
#  template: pipelines/dotnet.publish.nuget-v1.yml@sharedTemplates
steps:
- template: pipelines/dotnet.publish.nuget-v1.yml@sharedTemplates
  parameters:
    BuildConfiguration: ${{ parameters.BuildConfiguration }}
    CoverageInclude: '[nugget-app.*]*'
    gitHubConnection: github.com_mnastp